### ISSUE TITLE
[error]Task Failed. Error: 404

### ISSUE THREAD

**Issue by 3rk1n** [kasunkv/owasp-zap-vsts-task#58]
I created a VM on Azure and installed in Ubuntu. I installed Docker and Docker Image for OWASP ZAP which is reffered by https://www.zaproxy.org/docs/docker/webswing/. 

`docker run -u zap -p 8080:8080 -p 8090:8090 -i owasp/zap2docker-stable zap-webswing.sh`

Then I added CI step to scan.

```
stages:
- stage: devbuild
  displayName: Dev Build
  jobs:
  - job: Job_1
    displayName: Agent job 1
    pool:
      name: Azure Pipelines
    steps:
    - checkout: self
      fetchDepth: 1
    - task: OwaspZapScan@2
      inputs:
        ZapApiUrl: '<IP-Address-OWASP-VM>:8080'
        ZapApiKey: '<API-KEY>'
        TargetUrl: '<TARGET-URL>'
        ClearSession: true
        ExecuteSpiderScan: true
        RecurseSpider: true
        ExecuteActiveScan: true
        InScopeOnly: true
    - task: PublishHtmlReport@1
      inputs:
        reportDir: '$(System.DefaultWorkingDirectory)\OWASP-ZAP-Report-$(Build.BuildId).html'
```

At this point I get an error in below and CI ends with error message

`##[error]Task Failed. Error: “404 – \”\\n\\n\\nError 404 Not Found.\\n\\nHTTP ERROR 404 Not Found.\\n\\nURI:/JSON/core/action/newSession/\\nSTATUS:404\\nMESSAGE:Not Found.\\nSERVLET:WebswingServlet\\n\\n\\n\\n\\n\””`
